### ISSUE TITLE
AttributeError: module 'moonshine' has no attribute 'transcribe'

### ISSUE THREAD

**Issue by KuVa187** [usefulsensors/moonshine#51]
PS C:\Users\...> & "C:/Program Files/Python312/python.exe" .../moonshine1.py
Traceback (most recent call last):
  File "...\moonshine1.py", line 2, in <module>
    result = moonshine.transcribe(moonshine.ASSETS_DIR / r'path to audio file.mp3', 'moonshine/base')
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'moonshine' has no attribute 'transcribe'

Additional notes: I have no idea what im doing, help xD

**Comment by KuVa187** [comment]
oh and another question, how can i list my environments with uv?

**Comment by evmaki** [comment]
Without more information about your environment, I can't help with this error. But it's not moonshine, it probably has something to do with your environment (like trying to run your script without activating the environment first). Also be sure you don't have another script called `moonshine.py` in your project directory as this can confuse the imports.

To my knowledge there is no way to list your environments with `uv`. Environments are managed within the directories where you create them (as with `venv`). It is not like Conda where your environments are global.

**Comment by KuVa187** [comment]
nvm i did something wrong, but i dont know what. retried everything and it works now. is this even faster than whisperx? i don't think it is, but im no professional. btw, where are the enviroments located i installed? can they be deleted?

**Comment by KuVa187** [comment]
and another question, can moonshine not auto segment audio? do i really have to split my audio files into 60s parts?

**Comment by KuVa187** [comment]
UserWarning: You are using a softmax over axis 3 of a tensor of shape (1, 8, 1, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
Traceback (most recent call last):
  File "...\Moonshine\1.py", line 10, in <module>
    file.write(result)
TypeError: write() argument must be str, not list

**Comment by evmaki** [comment]
1. The use cases of moonshine and whisperX are different. WhisperX is indeed quite fast, but relies on a large amount of GPU memory to achieve these speed-ups. Moonshine is designed to run on resource-constrained devices like a Raspberry Pi, a mobile phone, your laptop, etc.

2. Our inference code currently doesn't support auto segmentation, but we are working on an update to include it.

3. The UserWarning comes from Keras and can be ignored; the TypeError has something to do with your own code. I am happy to provide as much info and support as I can about moonshine, but I unfortunately don't have enough bandwidth to provide Python programming support :)

Let me know if you have other questions. I will keep this open for the time being.

**Comment by KuVa187** [comment]
Ah ok, no other questions. Have a nice day
