### ISSUE TITLE
Live captions demo: fails to download and build during installation

### ISSUE THREAD

**Issue by guynich** [usefulsensors/moonshine#72]
I've hit this failure on several linux platforms: Ubuntu 22.04.2, Ubuntu 24.04.2 and Debian 12.8 when running this command.
```
uv pip install -r moonshine/demo/moonshine-onnx/requirements.txt
```
```
Using Python 3.10.12 environment at: env_moonshine_demo
 Updated https://git@github.com/usefulsensors/moonshine.git (a1d77cc)
Resolved 60 packages in 3.68s
   Built useful-moonshine-onnx @ git+https://git@github.com/usefulsensors/moonshine.git@a1d77cc573b0471ac4602b86f67b3f48d67df1a9#su
  × Failed to download and build `llvmlite==0.36.0`
  ╰─▶ Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/home/parallels/.cache/uv/builds-v0/.tmpoS52sI/lib/python3.10/site-packages/setuptools/build_meta.py", line
      334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/home/parallels/.cache/uv/builds-v0/.tmpoS52sI/lib/python3.10/site-packages/setuptools/build_meta.py", line
      304, in _get_build_requires
          self.run_setup()
        File "/home/parallels/.cache/uv/builds-v0/.tmpoS52sI/lib/python3.10/site-packages/setuptools/build_meta.py", line
      522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/home/parallels/.cache/uv/builds-v0/.tmpoS52sI/lib/python3.10/site-packages/setuptools/build_meta.py", line
      320, in run_setup
          exec(code, locals())
        File "<string>", line 55, in <module>
        File "<string>", line 52, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.10.12; only versions >=3.6,<3.10 are supported.

  help: `llvmlite` (v0.36.0) was included because `useful-moonshine-onnx` (v20241016) depends on `librosa` (v0.10.2.post1)
        which depends on `numba` (v0.53.1) which depends on `llvmlite`
```
A mitigation is to install `numba` package before running the command.
```
uv pip install numba
uv pip install -r moonshine/demo/moonshine-onnx/requirements.txt
```

**Comment by guynich** [comment]
A mitigation is described in https://github.com/usefulsensors/moonshine/pull/71.
