### ISSUE TITLE
locals()["__version__"] during installation on windows 11 with mingw64

### ISSUE THREAD

**Issue by mdzaebel** [usefulsensors/moonshine#74]
I get the following error during installation. Could you update revised instructions or show a workaround here?

locals()["__version__"] is an outdated practice and likely a bug in the package. Modern Python packaging tools like setuptools or poetry no longer require this approach, as versions are often managed directly in pyproject.toml or similar files.

```
$ pip install 'useful-moonshine[tensorflow] @ git+https://github.com/usefulsensors/moonshine.git'
Collecting useful-moonshine@ git+https://github.com/usefulsensors/moonshine.git (from useful-moonshine[tensorflow]@ git+https://github.com/usefulsensors/moonshine.git)
  Cloning https://github.com/usefulsensors/moonshine.git to c:\users\marc.dzaebel\appdata\local\temp\pip-install-c9a2o6zt\useful-moonshine_c81ef10e52f54530b27fb21a7196c56a
  Running command git clone --filter=blob:none --quiet https://github.com/usefulsensors/moonshine.git 'C:\Users\marc.dzaebel\AppData\Local\Temp\pip-install-c9a2o6zt\useful-moonshine_c81ef10e52f54530b27fb21a7196c56a'
  Resolved https://github.com/usefulsensors/moonshine.git to commit 6a0846b556ca1c1f2f373996fe53b0b79e23cc17
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [21 lines of output]
  C:\Users\marc.dzaebel\AppData\Local\Temp\pip-install-c9a2o6zt\useful-moonshine_c81ef10e52f54530b27fb21a7196c56a\setup.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
      exec(compile('''
      ~~~~^^^^^^^^^^^^
      # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ...<31 lines>...
      exec(compile(setup_py_code, filename, "exec"))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ''' % ('C:\\Users\\marc.dzaebel\\AppData\\Local\\Temp\\pip-install-c9a2o6zt\\useful-moonshine_c81ef10e52f54530b27fb21a7196c56a\\setup.py',), "<pip-setuptools-caller>", "exec"))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\marc.dzaebel\AppData\Local\Temp\pip-install-c9a2o6zt\useful-moonshine_c81ef10e52f54530b27fb21a7196c56a\setup.py", line 15, in <module>
      version=read_version(),
              ~~~~~~~~~~~~^^
    File "C:\Users\marc.dzaebel\AppData\Local\Temp\pip-install-c9a2o6zt\useful-moonshine_c81ef10e52f54530b27fb21a7196c56a\setup.py", line 9, in read_version
      return locals()["__version__"]
             ~~~~~~~~^^^^^^^^^^^^^^^
  KeyError: '__version__'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.
```

**Comment by keveman** [comment]
@mdzaebel Thanks for filing the issue. I am looking at how best to fix this, will update as soon as I have a solution.

**Comment by jambalaya1** [comment]
Seeing this on MacOS as well. Any workarounds for the time being?

**Comment by DottsGit** [comment]
This looks similar but not exactly the same.  Possibly relevant? Maybe its python version specific?

`(env_moonshine) PS C:\Users\lguxr\Documents\Programming\Community\moonshine> uv pip install useful-moonshine@git+https://github.com/usefulsensors/moonshine.git
Using Python 3.13.3 environment at: env_moonshine
  × Failed to build `useful-moonshine @                                        
  │ git+https://github.com/usefulsensors/moonshine.git`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit      
      code: 1)

      [stderr]
      <string>:3: DeprecationWarning: pkg_resources is deprecated as an API.   
      See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
          requires = get_requires_for_build({})
        File
      "C:\Users\lguxr\AppData\Local\uv\cache\builds-v0\.tmp7IQbmi\Lib\site-packages\setuptools\build_meta.py",
      line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])    
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
        File
      "C:\Users\lguxr\AppData\Local\uv\cache\builds-v0\.tmp7IQbmi\Lib\site-packages\setuptools\build_meta.py",
      line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File
      "C:\Users\lguxr\AppData\Local\uv\cache\builds-v0\.tmp7IQbmi\Lib\site-packages\setuptools\build_meta.py",
      line 512, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
      "C:\Users\lguxr\AppData\Local\uv\cache\builds-v0\.tmp7IQbmi\Lib\site-packages\setuptools\build_meta.py",
      line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 15, in <module>
          else:

        File "<string>", line 9, in read_version
      KeyError: '__version__'

      hint: This usually indicates a problem with the package or the build     
      environment.`
